openapi: 3.0.3
info:
  title: API of test spring application
  description: API of test spring application
  version: 1.0.0
servers:
  - url: 'https://localhost:8080'
tags:
  - name: account
    description: account management ,crud operation
paths:
  /account:
    tags: account
    summary: get account information
    description: get account information for specific user
    operationId: getAccount
    responses:
      200:
        description: success
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/account'

      400:
        description: not found
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountNotFoundError'

  /account/deposit:
    post:
      tags:
        - accounts
      summary: Deposit amount to account
      description: Initiates a deposit operation of a desired amount to the account specified
      operationId: depositToAccount
      requestBody:
        description: Account number and desired amount to deposit
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepositRequest'
        required: true
      responses:
        204:
          description: Success
        404:
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountNotFoundError'

components:
  schemas:
    Account:
      type: object
      properties:
        balance:
          type: number
    AccountNotFoundError:
      type: object
      properties:
        message:
          type: string
    DepositRequest:
      type: object
      properties:
        accountNumber:
          type: string
        depositAmount:
          type: number

  
